// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mdim_reduction_cpp
List mdim_reduction_cpp(List x, Function mdim_fun, IntegerVector row_indices, IntegerVector col_indices, int n_cells, int n_timepoints, int n_bands);
RcppExport SEXP _vrtility_mdim_reduction_cpp(SEXP xSEXP, SEXP mdim_funSEXP, SEXP row_indicesSEXP, SEXP col_indicesSEXP, SEXP n_cellsSEXP, SEXP n_timepointsSEXP, SEXP n_bandsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< Function >::type mdim_fun(mdim_funSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type row_indices(row_indicesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type col_indices(col_indicesSEXP);
    Rcpp::traits::input_parameter< int >::type n_cells(n_cellsSEXP);
    Rcpp::traits::input_parameter< int >::type n_timepoints(n_timepointsSEXP);
    Rcpp::traits::input_parameter< int >::type n_bands(n_bandsSEXP);
    rcpp_result_gen = Rcpp::wrap(mdim_reduction_cpp(x, mdim_fun, row_indices, col_indices, n_cells, n_timepoints, n_bands));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vrtility_mdim_reduction_cpp", (DL_FUNC) &_vrtility_mdim_reduction_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_vrtility(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
