# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extract_band_matrices_cpp <- function(x, row_indices, col_indices, n_cells, n_timepoints, n_bands) {
    .Call(`_vrtility_extract_band_matrices_cpp`, x, row_indices, col_indices, n_cells, n_timepoints, n_bands)
}

restructure_cells_cpp <- function(cell_vals) {
    .Call(`_vrtility_restructure_cells_cpp`, cell_vals)
}

