# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mdim_reduction_cpp <- function(x, mdim_fun, row_indices, col_indices, n_cells, n_timepoints, n_bands) {
    .Call(`_vrtility_mdim_reduction_cpp`, x, mdim_fun, row_indices, col_indices, n_cells, n_timepoints, n_bands)
}

